### ISSUE TITLE
how can i get your thesis?

### ISSUE THREAD

**Issue by wudehua2016** [shilch/CacheHound#1]
hi, shilch,
You have done an amazing job, and I greatly admire it.
What I want to know is, how can I get your Master's thesis titled "CacheHound: Automated Reverse-Engineering of CPU Cache Policies in Modern Multiprocessors"? The attached link is Unavailable. 
Thank you

**Comment by shilch** [comment]
Hi wudehua, thanks for your interest! I contacted the university and they fixed the link. You should be able to download a PDF there.

**Comment by wudehua2016** [comment]
thank you
